function ola () {
    const a + b = 0;

    a + b * 9
    a + b * 9
    a + b * 9
    sdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdasadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsaddfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdfsdfsdfsadfsadfsadfsdfsdfsadfsadfsadfasdfsdafsadfasdf
}